[package]
name = "wrkr"
authors = ["Ashlin Eldridge"]
description = "Performance characterization tool"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.6", features = ["cargo"] }
env_logger = "0.9.0"
humantime = "2.1.0"
hyper = { version = "0.14.17", features = ["full"] }
hyper-tls = "0.5.0"
log = "0.4.16"
tokio = { version = "1.17.0", features = ["full"] }
url = "2.2.2"
