[package]
name = "metron"
authors = ["Ashlin Eldridge"]
description = "Performance characterization tool"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["cargo"] }
env_logger = "0.9.0"
hdrhistogram = "7.5.0"
humantime = "2.1.0"
hyper = { version = "0.14.18", features = ["full"] }
hyper-tls = "0.5.0"
log = "0.4.17"
num_cpus = "1.13.1"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
url = "2.2.2"
