[package]
name = "metron"
authors = ["Ashlin Eldridge"]
description = "Performance characterization tool"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.2.5", features = ["cargo", "derive"] }
either = "1.6.1"
env_logger = "0.9.0"
hdrhistogram = "7.5.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
hyper = { version = "0.14.19", features = ["full"] }
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
log = "0.4.17"
metrics = "0.19.0"
metrics-exporter-prometheus = "0.10.0"
num_cpus = "1.13.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tower-http = "0.3.4"
url = { version = "2.2.2", features = ["serde"] }
