[package]
name = "wrkr"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"
humantime = "2.1.0"
hyper = { version = "0.14.16", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1.15.0", features = ["full"] }
