[workspace]
members = [
  "metron-app",
  "metron-config",
  "metron-core",  
  "metron-grpc",
]
resolver = "2"

[workspace.dependencies]
anyhow             = "1"
async-stream       = "0.3"
async-trait        = "0.1"
clap               = { version = "4.5", features = ["cargo", "derive"] }
either             = "1.13"
futures-core       = "0.3"
humantime          = "2.1"
humantime-serde    = "1.1"
num_cpus           = "1.16"
prost              = "0.13"
prost-types        = "0.13"
quanta             = { git = "https://github.com/ashlineldridge/quanta.git", rev = "0112215", features = ["prost"] }
reqwest            = "0.12"
serde              = { version = "1", features = ["derive"] }
serde_yaml         = "0.9"
tokio              = { version = "1", features = ["full"] }
tokio-stream       = "0.1"
tonic              = "0.12"
tonic-build        = "0.12"
tower              = { version = "0.5", features = ["discover", "ready-cache"] }
tracing            = "0.1"
tracing-core       = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url                = { version = "2.5", features = ["serde"] }
