[package]
name = "metron"
authors = ["Ashlin Eldridge"]
description = "Performance characterization tool"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["cargo"] }
env_logger = "0.9.0"
hdrhistogram = "7.5.0"
humantime = "2.1.0"
hyper = { version = "0.14.19", features = ["full"] }
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
log = "0.4.17"
num_cpus = "1.13.1"
prometheus = { version = "0.13.1", features = ["process", "push"] }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tower-http = "0.3.3"
url = "2.2.2"
