[package]
name = "metron-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace          = true
clap.workspace            = true
futures-core.workspace    = true
hdrhistogram = "7.5.4"
humantime-serde.workspace = true
quanta.workspace          = true
reqwest.workspace         = true
serde.workspace           = true
tokio.workspace           = true
tower.workspace           = true
tracing.workspace         = true
url.workspace             = true
