[package]
name = "metron-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace       = true
async-stream.workspace = true
async-trait.workspace  = true
metron-core            = { path = "../metron-core" }
prost-types.workspace  = true
prost.workspace        = true
quanta.workspace       = true
tokio-stream.workspace = true
tokio.workspace        = true
tonic.workspace        = true
tower.workspace        = true
tracing.workspace      = true
hdrhistogram = "7.5.4"

[build-dependencies]
tonic-build.workspace  = true
