[package]
name = "cli"
version = "0.1.0"
edition = "2021"
default-run = "metron"

[dependencies]
anyhow = "1.0.75"
echo = { path = "../echo" }
grpc = { path = "../grpc" }
infra = { path = "../infra" }
metron = { path = "../metron" }
operator = { path = "../operator" }
tokio = { version = "1.31.0", features = ["full"] }
