[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
prost = "0.11.9"
prost-types = "0.11.9"
tonic = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"
