name: remote-0
signaller: dedicated
worker_threads: 12
logging:
  level: debug
  format: bunyan
sinks:
- type: otel
  spec:
    address: http://localhost:8989/
    period:
      secs: 60
      nanos: 0
    timeout:
      secs: 60
      nanos: 0