# TODO: Rename to:
# MetronController
# MetronRunner
# MetronServer
# MetronClient
---
# Configuration required by run_local.
# Not required if runners: is specified.
runtime:
  signaller: dedicated # alt, "cooperative"
  worker_threads: 8
  connections: 4
runners:
  # Should these be HTTP URLs or is something else more appropriate?
  static:
  - http://localhost:9090
  - http://localhost:9091
  - http://localhost:9092
  # Later:
  # kubernetes:
  # - namespace: foobar
  #   labels:
  #   - name: foo
  #     value: bar
plan:
  segments:
  - kind: fixed
    rate: 100
    duration: 2m
  - kind: linear
    rate_start: 100
    rate_end: 200
    duration: 1m
  # Should this also go under runtime?
  connections: 8
  http_method: get
  targets:
  - https://foo.com/
  - https://bar.com/
  headers:
  - name: X-Metron-Foo
    value: foo
  - name: X-Metron-Bar
    value: bar
  payload: foobar
  # This should go up in runtime.
  worker_threads: 8
  latency_correction: true
# Not required if external runners are specified.
telemetry:
  otel:
    endpoint: blah
  local:
    format: json
---
# Configuration required by run_runner (bad name).
server_port: 9090
runtime:
  signaller: dedicated # alt, "cooperative"
  worker_threads: 8
  connections: 4
telemetry:
  otel:
    endpoint: blah
  local:
    format: json
---
# Configuration required by run_controller.
server_port: 9090
runtime:
  signaller: dedicated # alt, "cooperative"
  worker_threads: 8
  connections: 4
runners:
  # Should these be HTTP URLs or is something else more appropriate?
  static:
  - http://localhost:9090
  - http://localhost:9091
  - http://localhost:9092
  # Later:
  # kubernetes:
  # - namespace: foobar
  #   labels:
  #   - name: foo
  #     value: bar
