plan:
  name: myplan
  segments:
  - name: mysegment
    rate_start: 1.0
    rate_end: 1.0
    duration: 30s
  actions:
  - kind: http
    name: actionname
    target: http://httpbin.org/get
    method: get
    headers: {}
    payload: []
signaller: dedicated
worker_threads: 12
logging:
  level: debug
  format: bunyan
sinks:
- type: otel
  spec:
    address: http://localhost:8989/
    period:
      secs: 60
      nanos: 0
    timeout:
      secs: 60
      nanos: 0
