[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
# Only necessary if using Protobuf well-known types
# prost-types = "0.11"

[build-dependencies]
prost-build = "0.11"
