[package]
name = "metron"
version = "0.1.0"
edition = "2021"

[dependencies]
agent = { path = "../agent" }
anyhow = "1.0.75"
controller = { path = "../controller" }
echo = { path = "../echo" }
infra = { path = "../infra" }
operator = { path = "../operator" }
proto = { path = "../proto" }
tokio = { version = "1.31.0", features = ["full"] }
