syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

package proto;

// ----------------------------------------------------------------------------
// Agent Service

service Agent {
  // Create a control stream with the agent.
  rpc Control(stream ControlRequest) returns (stream ControlResponse);
}

// ----------------------------------------------------------------------------
// RPC Requests & Responses

message ControlRequest {
  Plan plan = 1;
  google.protobuf.Timestamp start = 2;
}

message ControlResponse {}

// ----------------------------------------------------------------------------
// Test Plan

message Plan {
  string name = 1;
  repeated Segment segments = 2;
  repeated Action actions = 3;
}

message Segment {
  string name = 1;
  float rate_start = 2;
  float rate_end = 3;
  google.protobuf.Duration duration = 4;
}

message Action {
  string name = 1;
  oneof action {
    HttpAction http_action = 2;
    UdpAction udp_action = 3;
    ExecAction exec_action = 4;
    WasmAction wasm_action = 5;
  }
}

message HttpAction {
  string target = 1;
  HttpMethod method = 2;
  map<string, string> headers = 3;
  bytes payload = 4;
}

enum HttpMethod {
  GET = 0;
  POST = 1;
  PUT = 2;
  PATCH = 3;
  DELETE = 4;
  HEAD = 5;
  OPTIONS = 6;
  TRACE = 7;
  CONNECT = 8;
}

message TcpAction {
  string target = 1;
  bytes payload = 2;
}

message UdpAction {
  string target = 1;
  bytes payload = 2;
}

message ExecAction {
  string command = 1;
  repeated string args = 2;
  map<string, string> env = 3;
}

message GrpcAction {
  // E.g. see https://docs.datadoghq.com/synthetics/api_tests/grpc_tests/?tab=behaviorcheck.
}

message WasmAction {
}
