[package]
name = "metron-config"
version = "0.1.0"
authors = ["Ashlin Eldridge <ashlin.eldridge@gmail.com>"]
edition = "2021"

[dependencies]
anyhow.workspace       = true
clap.workspace         = true
humantime.workspace    = true
metron-core            = { path = "../metron-core" }
serde.workspace        = true
thiserror.workspace    = true
tokio.workspace        = true
tracing-core.workspace = true
tracing.workspace      = true
url.workspace          = true
