[package]
name = "metron-app"
version = "0.1.0"
authors = ["Ashlin Eldridge <ashlin.eldridge@gmail.com>"]
edition = "2021"

[[bin]]
name = "metron"
path = "src/main.rs"

[dependencies]
anyhow.workspace             = true
clap.workspace               = true
either.workspace             = true
humantime.workspace          = true
metron-config                = { path = "../metron-config" }
metron-core                  = { path = "../metron-core" }
serde.workspace              = true
serde_yaml.workspace         = true
thiserror.workspace          = true
tokio.workspace              = true
tracing-core.workspace       = true
tracing-subscriber.workspace = true
tracing.workspace            = true
url.workspace                = true
num_cpus.workspace           = true
